#!/usr/bin/env python3
"""Transpiles the `smoke` namespace of typemeit/Overlay/Puff.metal to GLSL ES
3.00 and writes it to web/puff.glsl.js, so index.html renders the puff from
the same source as the app.

Metal Shading Language and GLSL share almost all of the subset the shader
uses; the differences are handled by plain substitution:

  float2/3/4 -> vec2/3/4      float2x2 -> mat2      half/half3/half4 -> float/vec3/vec4
  `static` dropped            saturate() supplied   namespace braces dropped

Anything outside the namespace (includes, the [[stitchable]] entry point) is
not translated; the entry point's job is done by main() in index.html.
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "typemeit" / "Overlay" / "Puff.metal"
OUT = pathlib.Path(__file__).resolve().parent / "puff.glsl.js"

metal = SRC.read_text()
start = metal.index("namespace smoke {") + len("namespace smoke {")
end = metal.index("} // namespace smoke")
body = metal[start:end]

subs = [
    (r"\bfloat2x2\b", "mat2"),
    (r"\bfloat2\b", "vec2"),
    (r"\bfloat3\b", "vec3"),
    (r"\bfloat4\b", "vec4"),
    (r"\bhalf4\b", "vec4"),
    (r"\bhalf3\b", "vec3"),
    (r"\bhalf\b", "float"),
    (r"^static ", ""),
]
for pattern, repl in subs:
    body = re.sub(pattern, repl, body, flags=re.M)

code_only = re.sub(r"//.*", "", body)
unsupported = re.findall(r"\b(half2|float3x3|float4x4|texture2d|thread|device|constant)\b", code_only)
if unsupported:
    raise SystemExit(f"Puff.metal uses constructs the transpiler does not handle: {sorted(set(unsupported))}")

# Words Metal allows as identifiers but GLSL ES 3.00 reserves. A local named
# `out` compiles in the app and fails to compile in the browser, which is the
# kind of drift nothing else here would catch.
reserved = re.findall(
    r"\b(in|out|inout|attribute|varying|uniform|layout|centroid|flat|smooth|"
    r"invariant|precision|lowp|mediump|highp|sampler|discard|coherent|volatile|"
    r"restrict|readonly|writeonly)\b",
    code_only,
)
if reserved:
    raise SystemExit(
        "Puff.metal uses names GLSL ES 3.00 reserves as keywords: "
        f"{sorted(set(reserved))}. Rename them in Puff.metal."
    )

glsl = (
    "// Generated by web/generate.py from typemeit/Overlay/Puff.metal. Do not edit.\n"
    "float saturate(float x) { return clamp(x, 0.0, 1.0); }\n"
    + body.strip("\n") + "\n"
)
# The GLSL is embedded in a JavaScript template literal, so it must not
# contain a backtick or "${"; comments in the Metal use backticks as quotes.
glsl = glsl.replace("`", "'")
if "${" in glsl:
    raise SystemExit("Puff.metal contains '${', which cannot be embedded in the template literal")

OUT.write_text(
    "// Generated by web/generate.py from typemeit/Overlay/Puff.metal. Do not edit.\n"
    "const PUFF_GLSL = String.raw`\n" + glsl + "`;\n"
)
print(f"Wrote {OUT.relative_to(ROOT)} ({len(glsl.splitlines())} lines)")
